In [2]:
import numpy as np
a=np.array([1,2,3,4])
a+1

array([2, 3, 4, 5])

In [3]:
a**2

array([ 1,  4,  9, 16], dtype=int32)

In [4]:
#Arithmatic Operation Elementwise
b=np.ones(4)+1
a-b

array([-1.,  0.,  1.,  2.])

In [5]:
a*b

array([2., 4., 6., 8.])

In [7]:
c=np.diag([1,2,3,4])
print(c*c)
print('*********************')
print(c.dot(c))

[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]
*********************
[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]


In [8]:
a=np.array([1,2,3,4])
b=np.array([1,4,3,6])
a==b

array([ True, False,  True, False])

In [9]:
a>b

array([False, False, False, False])

In [12]:
a=np.array([1,2,3,4])
b=np.array([5,4,3,7])
c=np.array([1,2,3,4])
np.array_equal(a,c)


True

In [14]:
#Logical operation
a=np.array([0,1,1,0],dtype=bool)
b=np.array([0,0,1,1],dtype=bool)
np.logical_or(a,b)


array([False,  True,  True,  True])

In [15]:
np.logical_and(a,b)

array([False, False,  True, False])

In [16]:
#Transendental_functions
a=np.arange(5)
np.sin(a)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [18]:
np.log(a)

C:\Users\Admin\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436])

In [19]:
np.exp(a)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [21]:
#Shape Mismatch
a=np.arange(4)
a+np.array([1,2])

ValueError: operands could not be broadcast together with shapes (4,) (2,) 

In [22]:
#Computing Sum of arrays
x=np.array([1,2,3,4])
np.sum(x)

10

In [23]:
x=np.array([[1,2],[2,2]])
x

array([[1, 2],
       [2, 2]])

In [24]:
x.sum(axis=0)

array([3, 4])

In [25]:
x.sum(axis=1)

array([3, 4])

In [27]:
#Reductions
x=np.array([1,3,2])
x.min()

1

In [28]:
x.max()

3

In [29]:
x.argmax()

1

In [30]:
x.argmin()

0

In [32]:
#Logical operation 
np.all([True,True,False])

False

In [33]:
np.any([True,False,False])

True

In [34]:
a=np.zeros((50,50))
np.any(a!=0)

False

In [35]:
np.all(a==a)

True

In [36]:
a=np.array([1,2,3,2])
b=np.array([2,2,3,2])
c=np.array([6,4,4,5])
((a<=b)&(b<=c)).all()

True

In [37]:
#Stats
x=np.array([1,2,3,1])
y=np.array([[1,2,3],[5,6,1]])
x.mean()

1.75

In [38]:
np.median(x)

1.5

In [39]:
np.median(y,axis=1)

array([2., 5.])

In [40]:
x.std()

0.82915619758885

In [63]:
data=np.loadtxt('check1.txt',skiprows=1,usecols = (2,3,4))
data

array([[ 21.,  65., 120.],
       [ 22.,  75., 130.],
       [ 23.,  70., 145.],
       [ 24.,  66., 150.],
       [ 25.,  70.,  85.],
       [ 28.,  80., 168.]])

In [60]:
Age,Weight,height=data.T
Age
Weight
height

array([120., 130., 145., 150.,  85., 168.])

In [65]:
data1=data[:,1:]
data1

array([[ 65., 120.],
       [ 75., 130.],
       [ 70., 145.],
       [ 66., 150.],
       [ 70.,  85.],
       [ 80., 168.]])

In [66]:
data1.std(axis=0)

array([ 5.16397779, 26.26785107])

In [68]:
np.argmax(data1,axis=0)

array([5, 5], dtype=int64)

In [69]:
np.argmax(data1,axis=1)

array([1, 1, 1, 1, 1, 1], dtype=int64)

In [70]:
#Flattening
a=np.array([[1,2,3],[4,5,6]])
a.ravel()

array([1, 2, 3, 4, 5, 6])

In [71]:
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [72]:
a.T.ravel()

array([1, 4, 2, 5, 3, 6])

In [73]:
#Reshape
a.shape

(2, 3)

In [76]:
b=a.ravel()
b

array([1, 2, 3, 4, 5, 6])

In [78]:
b=b.reshape(2,3)
b

array([[1, 2, 3],
       [4, 5, 6]])

In [79]:
b[0,0]=100
a

array([[100,   2,   3],
       [  4,   5,   6]])

In [83]:
#Reshape may return a copy
a=np.zeros((3,2))
b=a.T.reshape(3*2)
b[0]=50
a

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [90]:
#Sorting
a=np.array([[5,4,6],[2,3,2]])
b=np.sort(a,axis=1)
b

array([[4, 5, 6],
       [2, 2, 3]])

In [92]:
#Sorting with fancy indexing
a=np.argsort([4,3,1,2])
j=np.argsort(a)
j #Indices

array([3, 2, 0, 1], dtype=int64)

In [93]:
#Value of indices
a[j]

array([0, 1, 2, 3], dtype=int64)